### ISSUE TITLE
Data in wrong columns?

### ISSUE THREAD

**Issue by nickrsan** [ceff-tech/ffc_api_client#23]
Alyssa Obester
I think the observed data in the plot above might be mislabeled or be pulling something else. The observed two year flood shouldnt be larger than the 10 year flood. I'm looking at the FFC output for that data and the numbers are different (peak_10 is 20770, peak_20 is 16740, peak_50 is 7080)

Nick Santos
it should print out a table of the percentiles into the console when it's run - is that the output you're looking at, or did you run it through online? Just trying to figure out if it's that the plot doesn't match the data the R code shows, or if it's not right anywhere in the R code and my error would be earlier

Alyssa Obester
the numbers that I gave you above were from when I ran it with the eflows website. I'm looking at the percentiles from the r package now and weirdly the peak_10 is the same as above but the peak_50 and peak_20 are different numbers.

Nick Santos
Ok. Hmmm. I'll look into that. Could share the actual values with me? And how were you calculating the percentiles based on the online data. Just trying to think of all the places these could end up different

Alyssa Obester
yeah - the FFMs summary tab here has the percentiles. the peak magnitude percentile values are all the same though because they were calculated by ranking all the peaks 

the gage ID is 11336000

[FFC_output_McConnell_webFFC_dec11.xlsx](https://github.com/ceff-tech/ffc_api_client/files/4042967/FFC_output_McConnell_webFFC_dec11.xlsx)

**Comment by nickrsan** [comment]
@alyssaobester I think I know what's going on here and it's kind of concerning for all peak metrics. It *looks* like they use 2/5/10/20/50 to mean the "2 year flood", "5 year flood", etc, rather than the way the rest of the group uses it (understandable given the nomenclature). So, I've been using 10/20/50, but I should have been using 2/5/10. Given the number of NAs, looks like the other metrics should get the same treatment.

Did you have to rename the metrics in the spreadsheet you sent, or did it come out with those names? If the latter, seems like maybe under the hood they use the wrong names, but then output the right names?

**Comment by alyssaobester** [comment]
Huh, okay. I didn't rename anything.

**Comment by nickrsan** [comment]
OK, great - just uploaded a new version that renames all Peak metrics as if they're __-year flows rather than percentiles. Please use the new version for any additional testing!

Commit was 28d42d18c0d2e49b04124f2a7211949383063f4f

**Comment by nickrsan** [comment]
Ended up renaming these one more time in the following commit because apparently the predicted metrics had old names too.  The flow metrics data are now updated and the names have all been aligned again.
