### ISSUE TITLE
Make sure spring duration component observed vs predicted plot on same plot

### ISSUE THREAD

**Issue by alyssaobester** [ceff-tech/ffc_api_client#48]
Looks like the spring duration component plots observed and predicted values are on different plots 

![image](https://user-images.githubusercontent.com/28309135/75373353-010de480-587f-11ea-95b4-207caa43f50e.png)

**Comment by nickrsan** [comment]
Nice catch - looks like TNC's API gives a bad name for that metric. I'll file an issue with them and also see about correcting it within the pacakge in the meantime.

**Comment by kristaniguchi** [comment]
This also applies to the evaluate_alteration function

**Comment by kklausmeyer** [comment]
Thanks for flagging this-  I'm trying to replicate the API call that is generating the "SU_Du" name.  When I call "
https://flow-api.codefornature.org/v2/ffm/?comids=14993177&ffms=sp_dur" I get the ffm value as "sp_dur".  

When I call 
"https://flow-api.codefornature.org/v2/ffm/?comids=14993177&ffms=sp_du" I get an empty table.  @nickrsan  can you indicate the api call that is returning the incorrect name?

**Comment by nickrsan** [comment]
Dang it - I thought I'd tested this straight out of the API and it was an issue there, but I couldn't find the error and just traced it to a transformation in the package code and not the API. Sorry to waste your time (and sorry for the wait Alyssa and Kris)! Thanks for looking into it.

**Comment by nickrsan** [comment]
Resolved in 3a5251a8087eab55f0deafee6cee1ec969d73eca. Kris and Alyssa, this should be fixed if you reinstall the package.
