### ISSUE TITLE
For evaluate_alteration() only output FFMs for ffc_results and ffc_percentiles

### ISSUE THREAD

**Issue by kristaniguchi** [ceff-tech/ffc_api_client#51]
For evaluate_alteration() only output FFMs for ffc_results and ffc_percentiles.  Currently, function outputs additional metrics (for example, julian day metrics and peak timing metrics).   Can you also sort output tables by metric alphabetically?  That way user can have direct comparison of predicted vs observed metrics/percentiles.

**Comment by nickrsan** [comment]
Awesome - this makes sense all around - I'd thought the extra metrics weren't being returned (sorry to @ryanpeek who has been dealing with this too!). I think it makes sense to drop them from the output when `evaluate_alteration` or `evaluate_gage_alteration` are used.

**Comment by nickrsan** [comment]
OK, this should be addressed in the newest version 0.9.6.5. Please give it a test and let me know if it does what you wanted! Both the ffc_results and ffc_percentiles should no longer have the non-metrics that start with __ or the ones that end in _Julian. @ryanpeek just FYI too.

Commit that closed it was 4c4974dc259f11375519ac4a1f97dc450fb9d637
