### ISSUE TITLE
evaluate_alteration(), evaluate_gage_alteration(), and get_predicted_flow_metrics() not working

### ISSUE THREAD

**Issue by kristaniguchi** [ceff-tech/ffc_api_client#56]
Hi Nick, last week these functions (evaluate_alteration(), evaluate_gage_alteration(), and get_predicted_flow_metrics()) were working fine.  Now they no longer work (with same data/script) and give the following error after saving the DRH step:
[1] "Saving DRH to..."
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

I uninstalled and reinstalled the ffc api but still getting the same error.  Did something change in the code? Thanks!

**Comment by kklausmeyer** [comment]
Hi all-  we updated the functional flow API to include three new fields-  this may be causing an error in the get_predicted_flow_metrics() code.  To see the new schema with observed data added, use this URL for an example:  https://flow-api.codefornature.org/v2/ffm/?comids=15048349

**Comment by nickrsan** [comment]
Thanks Kirk - I was wondering if something changed in one of the APIs given the error here - I appreciate you chiming in here so quickly (and I know I owe you some email responses too!).

Kris, I'm readying some other changes to help make the package nicer for CEFF users, so I'll make the appropriate changes to fix this and include them in an update and let you know here once that's done today or tomorrow.

**Comment by kristaniguchi** [comment]
Sounds good! Thanks, Kirk and Nick!

**Comment by nickrsan** [comment]
Hi Kris,

I believe I incorporated the required fixes in the latest commit, along with other code. Please try again. I'm going to close this issue, but please reopen it if you still have problems.

The fix was included in f18833d72b70ad514ecaf054c2fc6184922cc286

**Comment by kristaniguchi** [comment]
Thanks, Nick!  Really appreciate all you’ve done for CEFF 😊 Good like at UC Merced!

Kris

--
Kris Taniguchi-Quan, PhD
Scientist
Southern California Coastal Water Research Project
3535 Harbor Blvd, Suite 110<https://maps.google.com/?q=3535+Harbor+Blvd,+Suite+110+%0D%0A+Costa+Mesa,+CA+92626+%0D%0A+Office:+(714&entry=gmail&source=g>
Costa Mesa, CA 92626<https://maps.google.com/?q=3535+Harbor+Blvd,+Suite+110+%0D%0A+Costa+Mesa,+CA+92626+%0D%0A+Office:+(714&entry=gmail&source=g>
Office: 714<https://maps.google.com/?q=3535+Harbor+Blvd,+Suite+110+%0D%0A+Costa+Mesa,+CA+92626+%0D%0A+Office:+(714&entry=gmail&source=g>-755-3221
kristinetq@sccwrp.org<mailto:kristinetq@sccwrp.org>
www.sccwrp.org<http://www.sccwrp.org/>
